#  __      __        _         _____          _ _             
#  \ \    / /       (_)       / ____|        | (_)            
#   \ \  / /__ _ __  ___  __ | |     ___   __| |_ _ __   __ _ 
#    \ \/ / _ \ '_ \| \ \/ / | |    / _ \ / _` | | '_ \ / _` |
#     \  /  __/ | | | |>  <  | |___| (_) | (_| | | | | | (_| |
#      \/ \___|_| |_|_/_/\_\  \_____\___/ \__,_|_|_| |_|\__, |
#                                                        __/ |
#                     By [VenixCoding - Devo]           |___/ 

support: "https://discord.gg/9rmEts5kxg"

# Recommended Currencies: EMERALD, GOLD_INGOT, REDSTONE, DIAMOND, GOLD_NUGGET
Currency: "REDSTONE"
Price: 16

# Press (F3 + H) in one time then you can see item id.
Repairable:
 - 310
 - 311
 - 312
 - 313
 - 276
 - 261
 - 279

Messages:
  prefix: "&8&l┃ &e&lAnvilRepair &8&l┃"
  no-permission: "%prefix% &cYou don't have permission to use it."
  no-enough: "%prefix% &cYou don't have enough %currency% to use it."
  no-repair: "%prefix% &cThis item isn't allowed to repair."
  cooldown: "%prefix% &cPlease wait for a while to use it again."
  repaired: "%prefix% &cThis item is already repaired."
  config-reload: "%prefix% &aSuccessfully reloaded the config file."
  invaild-usage: "%prefix% &cUsage: /repair reload"